[[docs]]
  name = "Software"
  weight = 10
  identifier = "software"
  url = "/docs/software/getting-started/"

[[docs]]
  name = "Hardware"
  weight = 11
  identifier = "hardware"
  url = "/docs/hardware/hardware"

[[docs]]
 name = "Blog"
 weight = 12
 identifier = "blog"
 url = "/blog/"

[[main]]
 name = "Docs"
 url = "/docs/"
 weight = 10

[[social]]
  name = "Hackaday"
  pre = "images/terminal.svg"
  url = "https://hackaday.io/project/168668-paperdink"

[[social]]
  name = "GitHub"
  pre = "images/github.svg"
  url = "https://github.com/rgujju/paperdink"

[[social]]
  name = "Instagram"
  pre = "images/instagram.svg"
  url = "https://www.instagram.com/paperd.ink/"

[[social]]
  name = "Twitter"
  pre = "images/twitter.svg"
  url = "https://twitter.com/paperddotink"

[[social]]
  name = "prasad@paperd.ink"
  pre = "images/mail.svg"
  url = "mailto:prasad@paperd.ink"

[[footer]]

